language: php

php:
  - 7.2
  - 7.3
  - 7.4

install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction

script:
  - mkdir -p build/logs

notifications:
  email:
    on_success: never
