language: php

php:
  - 8.1

install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction

script:
  - mkdir -p build/logs

notifications:
  email:
    on_success: never
